export const company = {
  companyName: 'Amambua Anthony Construction Ltd',
  shortName: 'AA',
  tagline: 'Building Trust. Delivering Quality.',
  description: 'Amambua Anthony Construction Ltd is a professional construction and supplies company delivering residential, commercial, institutional and infrastructure solutions across Cameroon.',
  about: 'Amambua Anthony Construction Ltd is a client-focused construction and supplies company delivering reliable building, civil works, renovation and infrastructure solutions. We help homeowners, businesses and institutions move from concept to completion with practical planning, professional execution and clear communication.',
  mission: 'To deliver dependable construction and engineering solutions through disciplined planning, responsible workmanship and transparent client communication.',
  vision: 'To become a trusted name in quality construction and infrastructure delivery, building lasting value for communities, businesses and institutions.',
  coreValues: ['Quality','Safety','Integrity','Reliability','Teamwork','Customer focus'],
  yearEstablished: '2014',
  phone: '+237 677 068 548',
  alternativePhone: '+237 677 068 548',
  whatsapp: '+237 677 068 548',
  email: 'tonyamambua@yahoo.com',
  address: 'Bamenda Commercial Avenue',
  city: 'Bamenda',
  region: 'North-West',
  country: 'Cameroon',
  mapsUrl: 'https://maps.google.com/?q=Bamenda%20Commercial%20Avenue%2C%20Bamenda%2C%20Cameroon',
  social: { facebook: 'https://facebook.com', instagram: 'https://instagram.com', linkedin: 'https://linkedin.com', tiktok: 'https://tiktok.com' },
  logo: '/logo-placeholder.svg',
  favicon: '/favicon.svg',
  businessHours: [{day:'Monday - Friday',hours:'8:00 AM - 5:00 PM'},{day:'Saturday',hours:'9:00 AM - 1:00 PM'},{day:'Sunday',hours:'Closed'}],
  statistics: [{value:'10+',label:'Years of experience'},{value:'250+',label:'Projects delivered'},{value:'99%',label:'Client satisfaction'},{value:'Cameroon',label:'Primary market'}],
  registration: 'RC/2024/12345 - Business Registration',
  certifications: ['Site Safety Compliance','Quality Assurance Procedures','Project Documentation Standards'],
  seo: { title: 'Amambua Anthony Construction Ltd | Construction & Supplies in Cameroon', description: 'Construction, civil engineering, road works, building works and infrastructure solutions in Cameroon.', keywords: ['construction company in Cameroon','building construction','civil engineering','road construction','construction supplies','building materials','construction contractors','infrastructure development'] }
};
